### ISSUE TITLE
Look into Monaco Editor

### ISSUE THREAD

**Issue by yikuansun** [yikuansun/webkitty#1]
https://codemirror.net/

**Comment by yikuansun** [comment]
https://microsoft.github.io/monaco-editor/

**Comment by yikuansun** [comment]
Monaco runs VS Code I think

Very cool :)

**Comment by MySpaceEmoCat** [comment]
Yo. I've forked your stuff. Gonna like... add Codemirror and modify it a bit in my fork... Hope you don't mind. Peace.
