### ISSUE TITLE
for Windows :

### ISSUE THREAD

**Issue by blackcrack** [yikuansun/webkitty#8]
hi,

nice Tool/Program, thank you for this, but  don't know for minimal Windows it is.. 
i have already Win7 at run.. (updates exist still)

"Ordering Systems : Windows 7, Windows Vista, Windows 8.x , windows 10/11"

would be nice if it is in Readme.md

Dependencies ? Net Framework or in wich Programming language is it wrote ?

best :)
Blacky

**Comment by yikuansun** [comment]
Hi,

Thanks for the advice. I have added operating systems and dependencies to the readme.
The code is written in JS using the Electron framework.

Thanks!
